site_name: Machine Gnostics
site_url: https://machinegnostics.com
site_description: A python library for machine learning and data science based on non-statistical methods.
site_author: Nirmal Parmar
copyright: 
  Copyright © 2026 Nirmal Parmar (Machine Gnostics)   |</a>   
  <a href="#__consent">Change cookie settings   |</a>
  <a href="https://docs.machinegnostics.com/latest/contact/">Contact us</a>

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    - scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light modee
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.footer
  custom_dir: overrides
  language: en

plugins:
  - privacy
  - search:
      lang: en
  - git-revision-date-localized
  - awesome-pages

repo_url: https://github.com/MachineGnostics/machinegnostics
repo_name: Machine Gnostics

nav:
  - Home: index.md
  - Consultancy: consultancy.md
  - Developers: developers.md
  - FAQ: faq.md
  - Contact: contact.md


markdown_extensions:
  - def_list
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # - pymdownx:inlinehilite
  # - pymdownx:snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 

extra:
  # announce: moved to overrides/main.html
  version:
    # provider: mike
  analytics:
    provider: google
    property: G-CKN0D75GBF
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/MachineGnostics/machinegnostics
    name: Machine Gnostics on GitHub
  - icon: fontawesome/brands/discord
    link: https://discord.gg/WMMUaeJe2X
    name: Join us on Discord
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/109036022/
    name: Machine Gnostics on LinkedIn
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/machinegnostics/
    name: Machine Gnostics on PyPI
  - icon: fontawesome/brands/instagram
    link: https://www.instagram.com/machinegnostics/
    name: Machine Gnostics on Instagram
  - icon: fontawesome/brands/youtube
    link: https://www.youtube.com/@MachineGnostics
    name: Machine Gnostics on YouTube
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/cookie-consent.js
  - javascripts/vertical-colors.js
  - javascripts/home-dynamics.js